export const WELLBEING_PROMPTS = [
  { text: "What felt quietly meaningful today, even if it was small?", category: "gratitude" },
  { text: "Where did you notice kindness today — from yourself or someone else?", category: "connection" },
  { text: "What emotion showed up most today, and where did you feel it in your body?", category: "awareness" },
  { text: "What is one thing you can gently release for tonight?", category: "release" },
  { text: "What are you proud of handling today, imperfectly but honestly?", category: "growth" },
  { text: "If your day had a weather pattern, what would it be and why?", category: "reflection" },
  { text: "Who or what helped you feel steadier today?", category: "support" },
  { text: "What boundary protected your energy today, or what one might help tomorrow?", category: "boundaries" },
  { text: "What thought kept circling, and what might it be trying to tell you?", category: "awareness" },
  { text: "Describe a moment of ease — even thirty seconds of calm.", category: "calm" },
  { text: "What would “good enough” look like for tomorrow morning?", category: "intention" },
  { text: "Write a short note of compassion to yourself as if to a friend.", category: "self-compassion" },
  { text: "What surprised you about yourself today?", category: "growth" },
  { text: "Where did you say yes when you meant no — or no when you meant yes?", category: "honesty" },
  { text: "What are three sensory details from today (sounds, light, textures)?", category: "presence" },
  { text: "What story are you telling yourself right now, and is there a kinder version?", category: "perspective" },
  { text: "What drained you today, and what restored you even a little?", category: "energy" },
  { text: "If you could rename today with a book title, what would it be?", category: "reflection" },
  { text: "What do you need more of this week — rest, play, clarity, or company?", category: "needs" },
  { text: "What unfinished thought can wait until morning?", category: "release" },
  { text: "Who made you feel seen lately, and what did they do?", category: "connection" },
  { text: "What is one small joy you almost overlooked?", category: "gratitude" },
  { text: "How did you take care of your body today?", category: "wellbeing" },
  { text: "What are you learning about your own resilience lately?", category: "growth" },
  { text: "Write freely for a few minutes with no goal — what wants to be written?", category: "free" },
  { text: "What does safety feel like for you in this season of life?", category: "safety" },
  { text: "Where did curiosity show up today instead of judgment?", category: "mindfulness" },
  { text: "What hope are you carrying into the evening?", category: "hope" },
  { text: "If today were a letter to your future self, what would you keep?", category: "memory" },
  { text: "What is one kind next step you can take that is actually doable?", category: "intention" },
] as const;

export * from "./schemas";
